### ISSUE TITLE
(electron) loadUrl is deprecated. Use loadURL instead.

### ISSUE THREAD

**Issue by unional** [juliangruber/electron-stream#14]
I saw this warning when using `tape-run` which uses `browser-run` which uses `electron-stream`

Could this be the cause?
https://github.com/juliangruber/electron-stream/blob/af0ded6ffa880f7fda840ab19cba932b3c7468ad/lib/runner.js#L23

**Comment by juliangruber** [comment]
thanks for reporting! fixed in 2.6.1

**Comment by unional** [comment]
Electron just came out with two more deprecations. Forgot the names right now. Do you aware of it?

**Comment by juliangruber** [comment]
nope :/ let's wait till someone complains :)

**Comment by unional** [comment]
Let me complains. :stuck_out_tongue_winking_eye: 
They are:
(electron) node-integration is deprecated. Use nodeIntegration instead.
(electron) options.preload is deprecated. Use options.webPreferences.preload instead.

**Comment by juliangruber** [comment]
pull requests wellcome :)

**Comment by unional** [comment]
lol. Sure.
