### ISSUE TITLE
Syntax Error Problem

### ISSUE THREAD

**Issue by envatoodie** [juliangruber/electron-stream#23]
Affected version 5.0.0 - 5.0.5

I run into an error.
When I try to run:
`'console.log("<script></script>");' | electron-stream`
It returns:
`SyntaxError: Invalid or unexpected token`

When I run:
`'console.log("<script><\/script>");' | electron-stream`
It returns the expected result:
`<script></script>`

**Comment by juliangruber** [comment]
the `</script>` will have to be escaped. not sure what the proper method is here

**Comment by envatoodie** [comment]
Is there a reason why it needs to be escaped?

**Comment by juliangruber** [comment]
yes, because it's valid html and will tell the browser to close the current script tag
