### ISSUE TITLE
Unnecessary inner server when using browser-run

### ISSUE THREAD

**Issue by 3cp** [juliangruber/electron-stream#28]
I got some [strange lock-up in windows](https://travis-ci.org/dumberjs/dumber-module-loader/builds/542087047) when running `browser-run --static .` with all latest npm dependencies.

Not sure exactly which dependency caused the window issue. But when I dig deeper, it seems the inner http server in electron-stream is unnecessary when browser-run calls this module.

I was able to somehow bypass the windows issue by force electron-stream to reuse the http server created by browser-run.

```js
Electron.prototype._onfinish = function(){
  var self = this;
  var cb = this._spawn.bind(this)
  if (this.killed) return;
  this.source.push(null);

  // When browser-run runs this,
  // use the server booted by browser-run,
  // instead of creating new one in _createSourceUrl.
  if (this.opts.loc) {
    return cb(this.opts.loc);
  }

  if (this.opts.nodeIntegration) {
    return this._createNodeUrl(cb)
  }

  this._createSourceUrl(cb);
};
```

Let me know if this makes sense.

**Comment by juliangruber** [comment]
Hmm this is weird! I don't have access to a windows machine right now. Would you be interested in owning this and creating PR(s) for it?

**Comment by 3cp** [comment]
As I said, I am not sure this is the cause of my Windows issue. But if you think this special support of browser-run makes sense, I can create a PR.

**Comment by 3cp** [comment]
Might be ecstatic related https://github.com/indexzero/http-server/issues/534
